#!/bin/bash

echo "HideDesktop 应用测试说明"
echo "========================"
echo ""
echo "应用已启动，请检查以下内容："
echo ""
echo "1. 菜单栏检查："
echo "   - 在屏幕顶部菜单栏应该能看到一个电脑图标"
echo ""
echo "2. 功能测试："
echo "   - 点击菜单栏的电脑图标"
echo "   - 选择 '切换桌面显示' 或直接点击图标"
echo "   - 桌面图标应该被隐藏，显示当前壁纸"
echo "   - 再次点击可以恢复显示桌面图标"
echo ""
echo "3. 验证修复："
echo "   - 隐藏桌面时应该显示正确的壁纸图像"
echo "   - 不应该出现纯色块遮蔽"
echo "   - 壁纸应该按照系统设置的缩放模式显示"
echo ""
echo "4. 退出应用："
echo "   - 点击菜单栏图标，选择 '退出'"
echo ""
echo "修复的关键改进："
echo "- 使用正确的窗口层级 (CGWindowLevelForKey(.desktopIconWindow) + 1)"
echo "- 改进了壁纸加载和显示逻辑"
echo "- 支持多种壁纸缩放模式（充满屏幕、适合屏幕、拉伸、居中）"
echo "- 修复了窗口样式设置（使用空的 styleMask）"
